language: node_js
node_js:
  - 10
before_script:
  - cd example && yarn install
  - cd ../native-example && yarn install
  - cd ../native-package && yarn install
  - cd ../expo-package && yarn install
  - cd .. && yarn install
script:
  - yarn lint
  - yarn flow
  - yarn docs
  - yarn validate-translations
